// Transforms dashboard-frontend/src/index.css into a .cr-scope-wrapped
// stylesheet for the Capital Research module.
//
//   node scripts/scope-cr-css.mjs
//
// Rules:
//   - @import statements          → hoisted to top level (must precede all rules)
//   - @font-face blocks           → hoisted, unwrapped
//   - @keyframes blocks           → hoisted, unwrapped (animation names are global)
//   - :root { … } blocks          → hoisted, unwrapped (CSS variables on :root)
//   - everything else             → wrapped in `.cr-scope { … }` (compiled flat
//                                   by postcss-nested, configured in the build)
//   - body{…} / html{…} selectors → rewritten to `&` inside the wrapper (also
//                                   inside @media blocks)
//   - @media blocks               → stay nested inside the wrapper
//   - @page (only valid at top level / inside top-level @media) → extracted from
//     any @media block and re-emitted top level inside the same media condition
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '../../dashboard-frontend/src/index.css');
const OUT = resolve(here, '../src/modules/capital-research/capital-research.css');

const css = readFileSync(SRC, 'utf8');

// ── tiny top-level tokenizer: statements are either `…;` (at-statement) or
//    `prelude { … }` blocks with balanced braces. Comments are kept attached
//    to the statement that follows them.
function parseStatements(text) {
  const stmts = [];
  let i = 0;
  const n = text.length;
  let start = 0;
  while (i < n) {
    const ch = text[i];
    if (ch === '/' && text[i + 1] === '*') {           // comment
      i = text.indexOf('*/', i + 2);
      i = i === -1 ? n : i + 2;
    } else if (ch === '"' || ch === "'") {             // string
      const q = ch; i++;
      while (i < n && text[i] !== q) { if (text[i] === '\\') i++; i++; }
      i++;
    } else if (ch === ';') {
      stmts.push(text.slice(start, i + 1)); i++; start = i;
    } else if (ch === '{') {
      let depth = 1; i++;
      while (i < n && depth > 0) {
        const c = text[i];
        if (c === '/' && text[i + 1] === '*') {
          i = text.indexOf('*/', i + 2); i = i === -1 ? n : i + 2; continue;
        }
        if (c === '"' || c === "'") {
          const q = c; i++;
          while (i < n && text[i] !== q) { if (text[i] === '\\') i++; i++; }
        } else if (c === '{') depth++;
        else if (c === '}') depth--;
        i++;
      }
      stmts.push(text.slice(start, i)); start = i;
    } else {
      i++;
    }
  }
  const tail = text.slice(start).trim();
  if (tail) stmts.push(tail);
  return stmts;
}

// prelude of a block statement = everything before the first `{`, minus comments
function preludeOf(stmt) {
  const brace = stmt.indexOf('{');
  const raw = brace === -1 ? stmt : stmt.slice(0, brace);
  return raw.replace(/\/\*[\s\S]*?\*\//g, '').trim();
}

const hoisted = [];   // @import / @font-face / @keyframes / :root — top level
const wrapped = [];   // everything else — goes inside .cr-scope
const pageRules = []; // @page rules pulled out of @media blocks

for (const stmt of parseStatements(css)) {
  const p = preludeOf(stmt);
  if (
    p.startsWith('@import') ||
    p.startsWith('@font-face') ||
    p.startsWith('@keyframes') || p.startsWith('@-webkit-keyframes') ||
    /^:root(\s|$|,)/.test(p) || p === ':root'
  ) {
    hoisted.push(stmt.trim());
    continue;
  }

  let out = stmt;

  // body{…} / html{…} → &{…}  — selector must start a rule (after ; } { or
  // start of statement), so `tbody`, `.rpt-sub-body`, etc. are untouched.
  out = out.replace(
    /(^|[{};])(\s*)(?:html\s*,\s*body|body\s*,\s*html|body|html)(\s*(?:[,{]))/g,
    (m, pre, ws, post) => `${pre}${ws}&${post}`
  );

  // @page is only valid at top level (or in a top-level @media) — postcss-nested
  // would otherwise leave it stranded under .cr-scope. Pull it out of @media
  // blocks and re-emit it top level under the same media condition.
  if (p.startsWith('@media')) {
    const extracted = [];
    out = out.replace(/@page\b[^{]*\{[^{}]*\}/g, (m) => { extracted.push(m.trim()); return ''; });
    if (extracted.length) {
      pageRules.push(`${p} {\n  ${extracted.join('\n  ')}\n}`);
    }
  }

  wrapped.push(out.trim());
}

// @import must come before any other rule — order hoisted so imports lead.
hoisted.sort((a, b) =>
  (a.startsWith('@import') ? 0 : 1) - (b.startsWith('@import') ? 0 : 1)
);

const banner =
  '/* AUTO-GENERATED by frontend/scripts/scope-cr-css.mjs — do not edit by hand.\n' +
  '   Source: dashboard-frontend/src/index.css, scoped under .cr-scope\n' +
  '   (nesting is flattened by postcss-nested at build time). */\n';

const output =
  banner + '\n' +
  hoisted.join('\n\n') + '\n\n' +
  '.cr-scope {\n' +
  wrapped.join('\n\n') + '\n' +
  '}\n' +
  (pageRules.length ? '\n' + pageRules.join('\n\n') + '\n' : '');

writeFileSync(OUT, output, 'utf8');
console.log(
  `scope-cr-css: wrote ${OUT}\n` +
  `  hoisted: ${hoisted.length} statements (imports/font-face/keyframes/:root)\n` +
  `  wrapped: ${wrapped.length} statements under .cr-scope\n` +
  `  @page rules re-emitted top level: ${pageRules.length}`
);
